#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

$isDebug = filter_var(getenv('YII_DEBUG'), FILTER_VALIDATE_BOOLEAN);
$env = getenv('YII_ENV') ?: 'prod';

defined('YII_DEBUG') || define('YII_DEBUG', $isDebug);
defined('YII_ENV') || define('YII_ENV', $env);

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';
require __DIR__ . '/console/config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/common/config/main.php',
    require __DIR__ . '/common/config/main-local.php',
    require __DIR__ . '/console/config/main.php',
    require __DIR__ . '/console/config/main-local.php'
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
