#การนำเข้าข้อมูลเนื้อหา ไฟล์ Excel โดยมี Template ดังนี้

พืช/สัตว์/จุลินทรีย์
A3 = ชื่อเรือง
B3 = ชื่ออื่น
C3 = ลักษณะ/คุณสมบัติ
D3 = ประโยชน์
E3 = แหล่งที่พบ
F3 = พิกัด 
G3 = ภูมิภาค 
H3 = จังหวัด 
I3 = อำเภอ 
J3 = ตำบล 
K3 = รหัสไปรษณีย์ 
L3 = รูปภาพหน้าปก 
M3 = ข้อมูลอื่น ๆ ที่ฉันรู้ 
N3 = ฤดูกาลที่ใช้ประโยชน์ได้
O3 = ศักยภาพการใช้งานในชุมชน
P3 = ชื่อสามัญ
Q3 = ชื่อวิทยาศาสตร์
R3 = ชื่อวงศ์
S3 = รูปประกอบ
T3 = คำสำคัญ (Tags) 
U3 = แหล่งที่มาของภาพ 
V3 = แหล่งที่มาของข้อมูล
W3 = หมายเหตุ
X3 = สถานะ
Y3 = สัญญาอนุญาต (License)  
Z3 = การแสดงผล  

ข้อมูลภูมิปัญญา/ปราชญ์
A3 = หมวดหมู่ภูมิปัญญา/ปราชญ์
B3 = ชื่อเรื่อง
C3 = ชื่อ ผู้รู้/ปราชญ์
D3 = นามสกุล ผู้รู้/ปราชญ์
E3 = วัน/เดือน/ปีเกิด ของผู้รู้/ปราชญ์
F3 = ภูมิปัญญาที่เชี่ยวชาญ
G3 = รายละเอียด
H3 = แหล่งที่มาของภาพ
I3 = แหล่งที่มาของข้อมูล
J3 = อาชีพ ผู้รู้/ปราชญ์
K3 = เลขบัตรประชาชน ผู้รู้/ปราชญ์
L3 = โทรศัพท์ ผู้รู้/ปราชญ์
M3 = ที่อยู่ (บรรทัดที่ 1, optional)
N3 = พิกัด
O3 = ภูมิภาค
P3 = จังหวัด
Q3 = อำเภอ
R3 = ตำบล
S3 = รหัสไปรษณีย์
T3 = รูปภาพปก
U3 = รูปประกอบ (แสดงเป็น Gallery)
V3 = คำสำคัญ (Tags)
W3 = หมายเหตุ
X3 = สถานะ
Y3 = สัญญาอนุญาต (License)  
Z3 = การแสดงผล  

แหล่งท่องเที่ยวเชิงนิเวศ
A3 = ชื่อเรื่อง
B3 = รายละเอียด
C3 = แหล่งที่มาของภาพ
D3 = แหล่งที่มาของข้อมูล
E3 = อธิบายการเดินทาง
F3 = ที่อยู่ (บรรทัดที่ 1, optional)
G3 = พิกัด
H3 = ภูมิภาค
I3 = จังหวัด
J3 = อำเภอ
K3 = ตำบล
L3 = รหัสไปรษณีย์
M3 = รูปภาพปก
N3 = เบอร์โทรศัพท์
O3 = ชื่อผู้ติดต่อ
P3 = ข้อมูลการติดต่อ
Q3 = รูปประกอบ (แสดงเป็น Gallery)
R3 = คำสำคัญ (Tags)
S3 = หมายเหตุ
T3 = สถานะ
U3 = สัญญาอนุญาต (License)  
V3 = การแสดงผล  

ข้อมูลผลิตภัณฑ์ชุมชน
A3 = ชื่อเรื่อง
B3 = หมวดหมู่ผลิตภัณฑ์
C3 = จุดเด่น/ประโยชน์
D3 = ราคาขาย
E3 = สถานที่ผลิต/จำหน่าย
F3 = ที่อยู่ (บรรทัดที่ 1, optional)
G3 = ภูมิภาค
H3 = จังหวัด
I3 = อำเภอ
J3 = ตำบล
K3 = รหัสไปรษณีย์
L3 = เบอร์โทรศัพท์
M3 = พิกัด
N3 = วัตถุดิบหลัก
O3 = แหล่งวัตถุดิบ
P3 = รูปภาพปก
Q3 = แหล่งที่มาของภาพ
R3 = แหล่งที่มาของข้อมูล
S3 = แหล่งที่พบ
T3 = ข้อมูลการติดต่อ
U3 = รูปประกอบ (แสดงเป็น Gallery)
V3 = คำสำคัญ (Tags)
W3 = หมายเหตุ
X3 = สถานะ
Y3 = สัญญาอนุญาต (License)  
Z3 = การแสดงผล  